export const dataItems = [
  "Promotion",
  "Opportunity",
  "Development",
  "Luggage",
  "Happiness",
  "Experience",
  "Performance",
  "Artist",
  "Applicant",
  "Employee",
  "Representative",
  "Helpful",
  "Building",
  "Successful",
  "Achievable",
  "Confidential",
  "Expensive",
  "Famous",
  "Delicious",
  "Fantastic",
  "Dangerous",
  "Responsible",
  "International",
  "Careless",
  "Important",
  "Creative",
  "Healthy",
  "Appointment",
  "Description",
  "Replace",
  "Impression",
  "Presentation",
  "Construction",
  "Competition",
  "Prediction",
  "Nominate",
  "Treatment",
  "Headquarter",
  "The board of director",
  "Discussion",
  "Announce",
  "Speech",
  "Seminar",
  "Attendee",
  "Retirement party",
  " Reduced rate",
  "Resident",
  "Be held",
  "Award",
  "Conduct",
  "Grand opening",
  "Banquet",
  "Register",
  "Participate",
  "Guest",
  "Celebrate",
  "Interior Designer",
  "Investment",
  "Lecture",
  "In advance",
  "Provide",
  "Confirm",
  "Make a reservation",
  "Assignment",
  "Supervise",
  "Position",
  "Budget",
  "Approve",
  "Sign the contract",
  "Passenger",
  "Duration",
  "Revenue",
  "Fit",
  "Breakfast",
  "Candidate",
  "Survey",
  "Fill out",
  "Decade",
  "Recycle",
  "Contact",
  "Book",
  "Schedule",
  "Conference",
  "Consist of",
  "Assure",
  "Community",
  "Exihibition",
  "Process",
  "Convention center",
  "Drawer",
  "Prevent",
  "Goods",
  "Check",
  "Prize",
  "Client",
  "Spacious",
  "Inventory =  warehouse",
  "Increase",
  "Assistant",
  "Policy",
  "Event",
  "Attract",
  "Executive",
  "Attach",
  "Professional",
  "Submit",
  "Invoice",
  "Distribution",
  "Valid",
  "Contribute",
  "Explain",
  "Annual",
  "Career",
  "Request",
  "Result",
  "Feature",
  "Appreciate",
  "Complaint",
  "Improve",
  "Accounting",
  "Procedure",
  "Inform",
  "Personnel Department",
  "Apply for",
  "Experience",
  "Field of",
  "Advertise",
  "Purchase",
  "Rent",
  "President",
  "Return",
  "Account",
  "Colleague",
  "Reasonable price",
  "Security",
  "Proposal",
  "Audience",
  "Public transportation",
];
